# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 #testing
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    # Upload build artifact (optional)
    - name: Upload JAR
      uses: actions/upload-artifact@v4
      with:
        name: springboot-app
        path: target/*.jar
      
      
  deploy:

    runs-on: ubuntu-latest
    needs: build 
    
    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: springboot-app
    
      # Deploy via SCP
      - name: Copy artifact to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "*.jar"
          target: "/home/${{ vars.USERNAME }}/springboot-app/"
          
      # SSH into server & restart app
      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd springboot-app
            echo "Deploy was able to naviagate to the app folder"
            pkill -f 'java -jar' || true
            echo "Deploy got to the point of killing existing server app"
            nohup java -jar *.jar > app.log 2>&1 &
            echo "Deploy went past nohookup"
            exit 0
     
     
